name: food_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # Updated to Dart 3.x

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  path_provider_windows: ^2.1.0
  path_provider_linux: ^2.1.0
  badges: ^2.0.2
  cupertino_icons: ^1.0.8
  file: ^7.0.1
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  provider: ^6.1.1
  flutter_login: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/background_portrait.png
    - assets/images/logo.png

